#!/usr/bin/env python3

from debian import deb822
from subprocess import run as run_cmd
import glob
import os
import re
import logging
import json
import shutil

os.environ['DEBIAN_FRONTEND'] = 'noninteractive'
os.environ['PAGER'] = 'cat'

class AptWithSrc:
    def __init__(self, config_file, loglevel=logging.WARNING):
        self.logger = logging.getLogger()
        self.logger.setLevel(loglevel)
        self.logger.addHandler(logging.StreamHandler())
        self.build_depends = {}

        with open(config_file, 'r', encoding='utf-8') as f:
            self.cfg = json.load(f)

        if not 'sources' in self.cfg:
            raise

        with open(self.cfg['sources'], 'r', encoding='utf-8') as f:
            for paragraph in deb822.Sources.iter_paragraphs(f):
                package = paragraph.get('Package')
                build_depends = list(map(lambda s:s.split()[0], paragraph.get('Build-Depends').split(',')))
                if not build_depends:
                    self.logger.warning(f'{package}: no Build-Depends')
                version = paragraph.get('Version')
                if not version:
                    self.logger.warning(f'{package}: no Version')
                arch = paragraph.get('Architecture')
                if not arch:
                    self.logger.warning(f'{package}: no Architecture')
                self.build_depends[package] = build_depends

        for package in self.cfg['prebuilt-debs'].keys():
            self.build_depends[package] = []

    def is_installed(self, package):
        result = run_cmd(['dpkg', '-l', package], capture_output=True, text=True)
        if result.returncode == 0:
            for l in result.stdout.splitlines():
                if re.match('^ii', l):
                    return True
        return False

    def build_deb_from_git(self, package):
        run_cmd(['git', 'clone', self.cfg['git-repo'][package], package], check=True)
        org_path = os.getcwd()
        os.chdir(package)
        run_cmd(['dpkg-buildpackage', '-b', '-us', '-uc'], check=True)
        os.chdir(org_path)

    def copy_from_prebuilt(self, package):
        shutil.copy(os.path.join('prebuilt-debs', self.cfg['prebuilt-debs'][package]), self.cfg['prebuilt-debs'][package])

    def build_deb_from_apt_get_source(self, package):
        run_cmd(['apt-get', 'source', '-b', package], check=True)

    def build_deb_and_install(self, package):
        deb_files = glob.glob(package + '_*.deb')
        if len(deb_files) == 0:
            if self.build_depends[package]:
                run_cmd(['sudo', 'apt-get', 'build-dep', '-y', package], capture_output=True, text=True, check=True)
            if 'git-repo' in self.cfg and package in self.cfg['git-repo']:
                self.build_deb_from_git(package)
            elif 'prebuilt-debs' in self.cfg and package in self.cfg['prebuilt-debs']:
                self.copy_from_prebuilt(package)
            else:
                self.build_deb_from_apt_get_source(package)
            deb_files = glob.glob(package + '_*.deb')
        if len(deb_files) != 1:
            self.logger.error('deb_files:' + ', '.join(deb_files))
            raise
        deps = []
        result = run_cmd(['dpkg', '-I', deb_files[0]], capture_output=True, text=True, check=True)
        for l in result.stdout.splitlines():
            s = l.split(':', 1)
            if s[0].strip() == 'Depends':
                for dep in map(lambda x:re.split(r'[ :]', x.lstrip())[0], s[1].split(',')):
                    deps.append(dep)
                    self.install(dep)
        try:
            run_cmd(['sudo', 'dpkg', '-i', deb_files[0]], check=True)
        except:
            self.logger.error(f'{deb_files[0]} Depends: ' + ', '.join(deps))
            raise

    def install(self, package):
        if self.is_installed(package):
            return

        self.logger.info(f'Install {package}...')
        build_depends = self.build_depends.get(package)
        if build_depends is None:
            run_cmd(['sudo', 'apt-get', 'install', '-y', package], check=True)
        else:
            for dep in build_depends:
                self.install(dep)
            self.build_deb_and_install(package)

if __name__ == "__main__":
    apt_with_src = AptWithSrc('config.json', loglevel=logging.DEBUG)
    apt_with_src.install('ros-jazzy-ros-base')
